spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: A//4321abcd
    url: jdbc:mysql://localhost:3306/online_shop_user_schema
    hikari:
      auto-commit: true
  application:
    name: user-service
server:
  port: 50000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


