spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: developer
    password: A//4321abcd
    url: jdbc:mysql://localhost:3306/online_shop_shop_schema
    hikari:
      auto-commit: true
  application:
    name: shop-service
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #,http://localhost:8762/eureka
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
